import type { JSX } from "react";
import {
  FaBagShopping,
  FaBolt,
  FaBriefcase,
  FaBuilding,
  FaCar,
  FaFutbol,
  FaGem,
  FaGraduationCap,
  FaHandshakeAngle,
  FaHandsPraying,
  FaHeart,  
  FaLandmark,
  FaLocationDot,
  FaMasksTheater,
  FaMusic,
  FaPaw,
  FaPersonHiking,
  FaPersonSkiing,
  FaPersonSnowboarding,
  FaPeopleGroup,  
  FaQuestion,
  FaRing,
  FaShip,  
  FaSpa,
  FaTree,
  FaUmbrellaBeach,
  FaUser,  
  FaUsers,
  FaUtensils,
  FaClipboard,
} from "react-icons/fa6";
import { MdBackpack } from "react-icons/md";

// Map of trip categories to their corresponding icons
export const TRIP_CATEGORY_ICONS: Record<string, JSX.Element> = {
  solo: <FaUser />,
  couple: <FaHeart />,
  family: <FaUsers />,
  group: <FaPeopleGroup />,
  organized: <FaClipboard />,
  business: <FaBriefcase />,
  educational: <FaGraduationCap />,
  volunteering: <FaHandshakeAngle />,
  religious: <FaHandsPraying />,
  adventure: <FaPersonHiking />,
  nature: <FaTree />,
  backpacking: <MdBackpack />,
  roadtrip: <FaCar />,
  cruise: <FaShip />,
  luxury: <FaGem />,
  honeymoon: <FaRing />,
  wellness: <FaSpa />,
  local: <FaLocationDot />,
  food: <FaUtensils />,
  festival: <FaMusic />,
  sports: <FaFutbol />,
  shopping: <FaBagShopping />,
  beach: <FaUmbrellaBeach />,
  skiing: <FaPersonSkiing />,
  snowboarding: <FaPersonSnowboarding />,
  extreme: <FaBolt />,
  wildlife: <FaPaw />,
  historical: <FaLandmark />,
  architectural: <FaBuilding />,
  cultural: <FaMasksTheater />,
  other: <FaQuestion />,
};
