import { BsGrid } from "react-icons/bs";
import {
  FaArrowsRotate,
  FaBan,
  FaBarsProgress,
  FaBell,
  FaBinoculars,
  FaBolt,
  FaBookAtlas,
  FaBookmark,
  FaBug,
  FaCalendar,
  FaCalendarDay,
  FaCalendarDays,
  FaChartLine,
  FaChartSimple,
  FaCheck,
  FaChessKnight,
  FaCircleCheck,
  FaCircleHalfStroke,
  FaCircleInfo,
  FaCircleQuestion,
  FaCircleUser,
  FaCircleXmark,
  FaClapperboard,
  FaClipboardList,
  FaClock,
  FaCode,
  FaCoins,
  FaCompassDrafting,
  FaCopy,
  FaCrosshairs,
  FaDatabase,
  FaDesktop,
  FaDownload,
  FaEarthAmericas,
  FaEllipsisVertical,
  FaEye,
  FaEyeSlash,
  FaFileExport,
  FaFileImport,
  FaFilePen,
  FaFilter,
  FaFire,
  FaFlag,
  FaFloppyDisk,
  FaGamepad,
  FaGear,
  FaGlobe,
  FaHatWizard,
  FaHeart,
  FaHourglassStart,
  FaHouse,
  FaKeyboard,
  FaLandmark,
  FaLaptop,
  FaLaptopCode,
  FaLayerGroup,
  FaLeaf,
  FaLightbulb,
  FaLink,
  FaList,
  FaListCheck,
  FaLocationDot,
  FaLock,
  FaMagnifyingGlass,
  FaMap,
  FaMapLocationDot,
  FaMapPin,
  FaMedal,
  FaMobile,
  FaMoon,
  FaPaintbrush,
  FaPalette,
  FaPencil,
  FaPenToSquare,
  FaPercent,
  FaPlane,
  FaPlus,
  FaPowerOff,
  FaRegCircleQuestion,
  FaRegClock,
  FaRegEye,
  FaRegHeart,
  FaRightFromBracket,
  FaRocket,
  FaRotateLeft,
  FaShareFromSquare,
  FaShareNodes,
  FaShieldHalved,
  FaShuffle,
  FaSliders,
  FaSquarePlus,
  FaStar,
  FaSuitcaseRolling,
  FaSun,
  FaTablet,
  FaTag,
  FaTimeline,
  FaTrash,
  FaTriangleExclamation,
  FaTrophy,
  FaUser,
  FaUserGear,
  FaUserGroup,
  FaUserPlus,
  FaVolumeHigh,
  FaXmark,
} from "react-icons/fa6";
import { IoAccessibility, IoLanguage, IoTelescope } from "react-icons/io5";
import { PiCirclesFourFill } from "react-icons/pi";
import { TbSquaresSelected } from "react-icons/tb";
import { DashboardIcon } from "../components/media/icons/DashboardIcon";
import { VisitIcon } from "../components/media/icons/VisitIcon";

/** Centralized icon mapping for shared concepts */
export const ICONS = {
  // User
  account: FaCircleUser,
  profile: FaUser,
  location: FaLocationDot,
  friends: FaUserGroup,
  friendRequests: FaUserPlus,
  settings: FaGear,
  activity: FaRegClock,
  signOut: FaRightFromBracket,
  // Atlas
  atlas: FaEarthAmericas,
  map: FaMap,
  countries: FaGlobe,
  countryLists: FaListCheck,
  visits: VisitIcon,
  visitStatus: {
    home: FaHouse,
    visited: FaCircleCheck,
    future: FaClock,
    wantToVisit: FaHeart,
    notVisited: FaCircleXmark,
  },
  filters: FaFilter,
  layers: FaLayerGroup,
  markers: FaMapPin,
  legend: FaList,
  saved: FaBookmark,
  savedMaps: FaMapLocationDot,
  atlasMode: FaBookAtlas,
  timeline: FaTimeline,
  export: FaShareFromSquare,
  share: FaShareNodes,
  mapSettings: {
    base: FaGear,
    configuration: FaCompassDrafting,
    interface: FaSliders,
    overlays: TbSquaresSelected,
    colors: FaPalette,
  },
  // Explore
  explore: FaBinoculars,
  progress: FaBarsProgress,
  discover: IoTelescope,
  didYouKnow: FaLightbulb,
  currencies: FaCoins,
  timezones: FaClock,
  // Trips
  trips: FaSuitcaseRolling,
  tripDates: FaCalendarDays,
  tripDuration: FaHourglassStart,
  tripCategory: PiCirclesFourFill,
  tripTag: FaTag,
  tripLocal: FaLocationDot,
  tripAbroad: FaPlane,
  tripPlanned: FaClipboardList,
  tripUpcoming: FaCalendarDay,
  tripInProgress: FaHourglassStart,
  tripCompleted: FaCheck,
  tripCancelled: FaBan,
  tripFilters: FaPercent,
  // Dashboard
  dashboard: DashboardIcon,
  overview: FaHouse,
  achievements: FaMedal,
  statistics: FaChartSimple,
  // Quizzes
  quizzes: FaGamepad,
  gameplay: FaChessKnight,
  quizFlag: FaFlag,
  quizCapital: FaLandmark,
  quizEasy: FaLeaf,
  quizMedium: FaBolt,
  quizHard: FaFire,
  quizExpert: FaHatWizard,
  leaderboards: FaTrophy,
  //Settings
  home: FaHouse,
  language: IoLanguage,
  sound: FaVolumeHigh,
  accountManagement: FaUserGear,
  display: FaPaintbrush,
  theme: {
    device: FaCircleHalfStroke,
    light: FaSun,
    dark: FaMoon,
  },
  accessibility: IoAccessibility,
  shortcuts: FaKeyboard,
  motion: FaClapperboard,
  privacy: FaShieldHalved,
  analytics: FaChartLine,
  security: FaLock,
  device: {
    desktop: FaDesktop,
    laptop: FaLaptop,
    mobile: FaMobile,
    tablet: FaTablet,
  },
  // Misc
  search: FaMagnifyingGlass,
  calendar: FaCalendar,
  notifications: FaBell,
  help: FaCircleQuestion,
  helpTooltip: FaRegCircleQuestion,
  info: FaCircleInfo,
  warning: FaTriangleExclamation,
  reportBug: FaBug,
  appearance: FaMoon,
  //UI
  viewMode: {
    grid: BsGrid,
    list: FaList,
  },
  // Actions
  add: FaPlus,
  importFile: FaFileImport,
  exportFile: FaFileExport,
  show: FaEye,
  hide: FaEyeSlash,
  view: FaRegEye,
  download: FaDownload,
  edit: FaPenToSquare,
  save: FaFloppyDisk,
  rename: FaPencil,
  center: FaCrosshairs,
  favorite: FaHeart,
  unfavorite: FaRegHeart,
  rate: FaStar,
  duplicate: FaCopy,
  createList: FaSquarePlus,
  shareWith: FaUserPlus,
  copyLink: FaLink,
  remove: FaTrash,
  reset: FaRotateLeft,
  refresh: FaArrowsRotate,
  shuffle: FaShuffle,
  poweroff: FaPowerOff,
  close: FaXmark,
  selected: FaCheck,
  more: FaEllipsisVertical,
  // Docs
  getStarted: FaRocket,
  developers: FaCode,
  laptopCode: FaLaptopCode,
  data: FaDatabase,
  scripts: FaFilePen,
};
