import type { JSX } from "react";
import {
  FaUser,
  FaHeart,
  FaUsers,
  FaClipboardList,
  FaBriefcase,
  FaGraduationCap,
  FaHandsHelping,
  FaPrayingHands,
  FaHiking,
  FaTree,
  FaCar,
  FaShip,
  FaGem,
  FaRing,
  FaSpa,
  FaMapMarkerAlt,
  FaUtensils,
  FaMusic,
  FaFutbol,
  FaShoppingBag,
  FaUmbrellaBeach,
  FaSkiing,
  FaSnowboarding,
  FaBolt,
  FaPaw,
  FaLandmark,
  FaBuilding,
  FaTheaterMasks,
  FaQuestion,
} from "react-icons/fa";
import { FaPeopleGroup } from "react-icons/fa6";
import { MdBackpack } from "react-icons/md";

// Map of trip categories to their corresponding icons
export const TRIP_CATEGORY_ICONS: Record<string, JSX.Element> = {
  solo: <FaUser />,
  couple: <FaHeart />,
  family: <FaUsers />,
  group: <FaPeopleGroup />,
  organized: <FaClipboardList />,
  business: <FaBriefcase />,
  educational: <FaGraduationCap />,
  volunteering: <FaHandsHelping />,
  religious: <FaPrayingHands />,
  adventure: <FaHiking />,
  nature: <FaTree />,
  backpacking: <MdBackpack />,
  roadtrip: <FaCar />,
  cruise: <FaShip />,
  luxury: <FaGem />,
  honeymoon: <FaRing />,
  wellness: <FaSpa />,
  local: <FaMapMarkerAlt />,
  food: <FaUtensils />,
  festival: <FaMusic />,
  sports: <FaFutbol />,
  shopping: <FaShoppingBag />,
  beach: <FaUmbrellaBeach />,
  skiing: <FaSkiing />,
  snowboarding: <FaSnowboarding />,
  extreme: <FaBolt />,
  wildlife: <FaPaw />,
  historical: <FaLandmark />,
  architectural: <FaBuilding />,
  cultural: <FaTheaterMasks />,
  other: <FaQuestion />,
};
